// <auto-generated />
namespace Cinemas.API.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsAddingUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsAddingUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201902180655488_IsAddingUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
